### ISSUE TITLE
can you provide operation manual for this  script?

### ISSUE THREAD

**Issue by zzsczz** [fpoussin/jlcpcb-scripts#1]
I install  miniconda3   and  xlsxwriter;

I run the script 

python eagle2jlc.py sch1.brd

and  get error :  

ValueError: check_hostname requires server_hostname

hao to fix this?

**Comment by fpoussin** [comment]
This looks like an issue with your Python installation, it's hard to guess without the full traceback. 
Try to install an official Python 3 release.
You can use --help to get the required parameters.
